### ISSUE TITLE
tsc type error

### ISSUE THREAD

**Issue by snarky-puppy** [hexlabsio/dynamo-ts#59]
Started getting a compile error after upgrading to 6.x.x:

```
test-proj % node --version
v22.10.0
```

```json
{
  "name": "test-proj",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.716.0",
    "@aws-sdk/lib-dynamodb": "^3.716.0",
    "@hexlabs/dynamo-ts": "^6.0.193",
    "typescript": "^5.7.2"
  }
}
```

```typescript
import {TableDefinition} from '@hexlabs/dynamo-ts';

export type FooRecord = {
  id: string;
  foo: string;
  bar: string;
  baz: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};

const fooTableDef = TableDefinition.ofType<FooRecord>()
  .withPartitionKey('id')
  .withGlobalSecondaryIndex('baz-idx', 'baz')
  .withSortKey('createdAt');
```

```
test-proj % yarn tsc db.ts
yarn run v1.22.19
$ /private/tmp/test-proj/node_modules/.bin/tsc db.ts
../node_modules/@types/node/module.d.ts:107:13 - error TS2386: Overload signatures must all be optional or required.

107             resolve?(specified: string, parent?: string | URL): Promise<string>;
                ~~~~~~~

node_modules/@hexlabs/dynamo-ts/dist/esm/table-client.d.ts:92:123 - error TS2344: Type 'TableConfig["indexes"][Index]' does not satisfy the constraint 'DynamoTableKeyConfig<TableConfig["type"]>'.
  Type 'TableConfig["indexes"][keyof TableConfig["indexes"]]' is not assignable to type 'DynamoTableKeyConfig<TableConfig["type"]>'.
    Type 'TableConfig["indexes"][string] | TableConfig["indexes"][number] | TableConfig["indexes"][symbol]' is not assignable to type 'DynamoTableKeyConfig<TableConfig["type"]>'.
      Type 'TableConfig["indexes"][string]' is not assignable to type 'DynamoTableKeyConfig<TableConfig["type"]>'.

92     index<Index extends keyof TableConfig['indexes']>(indexName: Index): IndexClient<TableDefinition<TableConfig['type'], TableConfig['indexes'][Index]>>;
                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  ../node_modules/@types/node/module.d.ts:107
     1  node_modules/@hexlabs/dynamo-ts/dist/esm/table-client.d.ts:92
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by chrisbarbour** [comment]
@snarky-puppy Thanks for this! This is caused by a change in typescript which conflicts with older versions of `@types/node` I have a PR (#60) that will bring the types up to date and also includes a more up-to-date version of node types in dev dependencies. I will let you know once merged.

**Comment by chrisbarbour** [comment]
The latest version should work for you, make sure to include types for node: 
```
    "@types/node": "^20.17.10"
```
